### PR TITLE
Style fixes

### PR DESCRIPTION
**Pull request by sourabhvarshney111**
I am trying to optimize the code through direct calling the ValidateScore Function rather than calculating score in the test itself.Moreover, I have done some style fixes.

Edit: Done : )

### CODE REVIEW

**Comment by Manthan-R-Sheth** [comment]
@sourabhvarshney111  I had thought of doing so but i didn't want to mix up ValidateScore() in this test. We need to perform a separate test for VaidateScore() too (what if some error is present there).

**Comment by sourabhvarshney111** [comment]
But, what we have used is the same algorithm as in the Validate Score. So, can't we first check the validate score function and then use the optimized version?

**Comment by Manthan-R-Sheth** [comment]
ya @sourabhvarshney111  thats the plan exactly. Once zoq and rcurtin approve of the changes, we can update it to the optimised version.

**Comment by sourabhvarshney111** [comment]
@Manthan-R-Sheth  I have resolved the conflicts. You can check it before the merge.

**Pull request merged**
